spring.application.name=back-parceria
server.port=${PORT:8080}

# Instrução que manda o Spring Boot carregar o arquivo .env da raiz do projeto
spring.config.import=optional:file:.env[.properties],optional:file:back-parceria/.env[.properties]

# Configuração API do Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:soujunior.parcerias@gmail.com}
spring.mail.password=${MAIL_PASSWORD}

# CONFIGURAÇÕES DA GMAIL API COM FALLBACKS PARA TESTES/CI
gmail.client.id=${GMAIL_CLIENT_ID:seu_client_id_padrao}
gmail.client.secret=${GMAIL_CLIENT_SECRET:seu_client_secret_padrao}
gmail.refresh.token=${GMAIL_REFRESH_TOKEN:seu_refresh_token_padrao}

spring.mail.username=${SPRING_MAIL_USERNAME:soujunior.parcerias@gmail.com}
app.email.destino=${EMAIL_DESTINO:soujunior.parcerias@gmail.com}