spring.application.name=back-parceria
server.port=8080

# Instrução que manda o Spring Boot carregar o arquivo .env da raiz do projeto
spring.config.import=optional:file:.env[.properties],optional:file:back-parceria/.env[.properties]

# Configuração API do Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:soujunior.parcerias@gmail.com}
spring.mail.password=${MAIL_PASSWORD}

# Configuração STARTTLS (Livre de bloqueio SSL/Handshake)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

app.email.destino=${EMAIL_DESTINO:soujunior.parcerias@gmail.com}

